# Generated by Django 2.1.2 on 2018-10-16 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='passwords',
        ),
    ]
