# Generated by Django 2.1.2 on 2018-10-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0002_remove_client_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pass_user',
            field=models.TextField(default=False),
        ),
    ]
