# Generated by Django 2.1.2 on 2018-10-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0003_client_pass_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pass_user',
            field=models.CharField(max_length=20),
        ),
    ]
